name: Update User via Dispatch

on:
  repository_dispatch:
    types: [update_user]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qrcode pillow

      - name: Save payload
        run: echo '${{ toJson(github.event.client_payload) }}' > payload.json

      - name: Run update script
        run: python .github/scripts/update_user.py
